### ISSUE TITLE
macOS 添加自定义词典

### ISSUE THREAD

**Issue by ninehills** [ninehills/ninehills.github.io#61]
参考：<https://www.zhihu.com/question/20428599/answer/66420264>

此处仅摘录觉得不错的牛津、朗文、剑桥、柯林斯双解四合一，效果如下：

<img width="687" alt="2017-11-22 14 43 11" src="https://user-images.githubusercontent.com/270298/33113473-7b5711d4-cf93-11e7-9f82-a302e9776ce4.png">

```
链接: https://pan.baidu.com/s/1kVy2dsN 密码: tj1g
```

将词典文件（解压出的`OLCC.dictionary`）拷贝到 `~/Library/Dictionaries` 下，然后才词典的偏好设置中开启即可。

**Comment by lemonc747** [comment]
好用！另外打开词典界面后，选择文件=>打开字典文件夹，可以直达Dictionaries目录。

**Comment by wd** [comment]
这个不错，可以把其他词典都禁用了。感谢。

**Comment by witch61** [comment]
怎么把&nbsp去掉啊？

**Comment by YUFENGWANG** [comment]
还有其他的？

**Comment by SwJay** [comment]
这个dictionary文件有挺多问题的：1234链接跳转有问题，会出现&nbsp。

**Comment by xwhfcenter** [comment]
会出现&nbsp

**Comment by waninlezu** [comment]
黑暗主体 看着难受.
